# Generated by Django 3.0.7 on 2020-08-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
